### ISSUE TITLE
Xamarin Android difference and a DotNet Bug

### ISSUE THREAD

**Issue by cocoon** [lellis1936/CryptomatorAccessDemo#1]
Hi, thanks for your great work with this demo project!

As I love to work with csharp, I tried to use this after I failed to create a working "Binding Library" directly for the cryptolib.jar in Xamarin Forms for Android.

I wanted to create a private Android App that could directly read files from a cryptomator vault.

As your Demo was working great, I could easily use your helper in the Xamarin Forms App and even got rid of nearly all nuget dependencies, moved to netstandard 2.0.

BUT while it was working to decrypt the vault in Windows it fails in the Android app.

***Problems***

**miscreant.net**

I nailed it down (logging every return of values and compare side by side manually)  to this point in miscreant.net (encryptor.TransformFinalBlock):
https://github.com/miscreant/miscreant.net/blob/9909d640aa84f2aed18771c950028c33a7e2fe23/Miscreant/AesCmac.cs#L121

First difference is "encryptor.CanReuseTransform" is false with Android while true in Windows.

In the end the ciphertext is different on Android and the directory is not found (byte[] ciphertext = siv.Seal(new byte[0]);)
https://github.com/lellis1936/CryptomatorAccessDemo/blob/5a7ce40a9ba255d9df417af168ade3a70b8cc85f/CryptomatorHelper/V7CryptomatorHelper.cs#L80

**Dotnet Bug**

Searching for solutions I found this Dotnet Bug that was fixed in 4.6.2, as your project was still on 4.6.1 I was hoping it would solve it or reproduce it on windows, but up to now I did not succeed:
https://github.com/microsoft/dotnet/blob/master/Documentation/compatibility/aescryptoserviceprovider-decryptor-provides-a-reusable-transform.md

https://stackoverflow.com/a/43598850

Any hint or replacement for this would be cool!

**Examples**

Windows

```
AesCmac HashFinal: 96-67-5E-74-5E-F2-37-08-45-36-5B-07-47-09-AF-8B

AesCmac HashFinal BlockSize: 16

AesCmac HashFinal encryptor.CanReuseTransform: True

AesCmac HashFinal encryptor.CanTransformMultipleBlocks: True

Seal iv: 96-67-5E-74-5E-F2-37-08-45-36-5B-07-47-09-AF-8B
Seal output1: 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
Seal output2: 96-67-5E-74-5E-F2-37-08-45-36-5B-07-47-09-AF-8B
Seal output3: 96-67-5E-74-5E-F2-37-08-45-36-5B-07-47-09-AF-8B
Seal output4: 96-67-5E-74-5E-F2-37-08-45-36-5B-07-47-09-AF-8B
Seal output5: 96-67-5E-74-5E-F2-37-08-45-36-5B-07-47-09-AF-8B
Seal plaintext: 
Seal Empty: 
Seal iv: 96-67-5E-74-5E-F2-37-08-45-36-5B-07-47-09-AF-8B
Seal output2: 96-67-5E-74-5E-F2-37-08-45-36-5B-07-47-09-AF-8B
Seal plaintext.Length: 0
Seal iv.Length: 16

V7CryptomatorHelper

abPrimaryMasterKey: 7C-52-6E-4A-94-3C-C0-2A-80-5A-24-8B-B5-40-BC-D7-D8-5C-E4-A3-87-FF-35-97-E6-F3-52-88-64-9F-68-65-59-BD-D9-AD-E2-81-4B-E8
abHmacMasterKey: 65-6E-F9-0A-BA-62-DB-CE-44-8F-07-0A-1A-31-0E-3F-42-94-3A-56-E8-BE-AE-D0-8D-0F-47-FE-7F-F4-C7-7B-C7-8A-E7-13-3A-ED-27-05
abScryptSalt: EA-F0-56-84-3F-24-02-37
kek: D4-B3-67-E1-A6-87-54-92-E2-13-5D-A5-75-20-D8-16-7C-29-1A-8A-04-F6-5C-02-15-64-E2-2A-BA-AE-0D-CF
masterKey: 8A-72-B4-63-B6-31-69-FD-3C-31-DE-82-31-F8-69-36-41-CD-24-15-27-BD-F8-FC-8A-5E-EE-08-21-80-59-EB
macKey: EA-63-CA-B8-CF-61-8F-96-BE-EC-28-CC-EF-F1-9B-E1-0A-BB-41-5C-F2-B6-6E-9E-AD-D8-B5-A5-49-2E-CE-69
sivKey: EA-63-CA-B8-CF-61-8F-96-BE-EC-28-CC-EF-F1-9B-E1-0A-BB-41-5C-F2-B6-6E-9E-AD-D8-B5-A5-49-2E-CE-69-8A-72-B4-63-B6-31-69-FD-3C-31-DE-82-31-F8-69-36-41-CD-24-15-27-BD-F8-FC-8A-5E-EE-08-21-80-59-EB
new byte[0]: 
ciphertext: 96-67-5E-74-5E-F2-37-08-45-36-5B-07-47-09-AF-8B
hash: 96-67-5E-74-5E-F2-37-08-45-36-5B-07-47-09-AF-8B
fullDirName: MV4GZEO6F54SH247AZHPEEGOCGZQVUJA
physicalPathRoot: MV\4GZEO6F54SH247AZHPEEGOCGZQVUJA

Xor2 source: 3F-1A-24-85-E4-2F-33-23-8E-5B-A1-0B-93-3D-87-37

Xor2 source.Length: 16
```

Android
```
08-28 21:43:09.945 I/mono-stdout(30771): AesCmac HashFinal: 43-D7-43-09-A1-75-09-DE-A4-39-4A-20-7C-96-D5-EB
08-28 21:43:09.945 I/mono-stdout(30771): 
08-28 21:43:09.945 I/mono-stdout(30771): AesCmac HashFinal BlockSize: 16
08-28 21:43:09.945 I/mono-stdout(30771): 
08-28 21:43:09.945 I/mono-stdout(30771): AesCmac HashFinal encryptor.CanReuseTransform: False
08-28 21:43:09.945 I/mono-stdout(30771): 
08-28 21:43:09.945 I/mono-stdout(30771): AesCmac HashFinal encryptor.CanTransformMultipleBlocks: True
08-28 21:43:09.945 I/mono-stdout(30771): 
08-28 21:43:09.945 I/mono-stdout(30771): Seal iv: 43-D7-43-09-A1-75-09-DE-A4-39-4A-20-7C-96-D5-EB
08-28 21:43:09.945 I/mono-stdout(30771): Seal output1: 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
08-28 21:43:09.946 I/mono-stdout(30771): Seal output2: 43-D7-43-09-A1-75-09-DE-A4-39-4A-20-7C-96-D5-EB
08-28 21:43:09.946 I/mono-stdout(30771): Seal output3: 43-D7-43-09-A1-75-09-DE-A4-39-4A-20-7C-96-D5-EB
08-28 21:43:09.946 I/mono-stdout(30771): Seal output4: 43-D7-43-09-A1-75-09-DE-A4-39-4A-20-7C-96-D5-EB
08-28 21:43:09.946 I/mono-stdout(30771): Seal output5: 43-D7-43-09-A1-75-09-DE-A4-39-4A-20-7C-96-D5-EB
08-28 21:43:09.946 I/mono-stdout(30771): Seal plaintext: 
08-28 21:43:09.946 I/mono-stdout(30771): Seal Empty: 
08-28 21:43:09.946 I/mono-stdout(30771): Seal iv: 43-D7-43-09-A1-75-09-DE-24-39-4A-20-7C-96-D5-EB
08-28 21:43:09.946 I/mono-stdout(30771): Seal output2: 43-D7-43-09-A1-75-09-DE-24-39-4A-20-7C-96-D5-EB
08-28 21:43:09.946 I/mono-stdout(30771): Seal plaintext.Length: 0
08-28 21:43:09.946 I/mono-stdout(30771): Seal iv.Length: 16
08-28 21:43:09.946 I/mono-stdout(30771): 
08-28 21:43:09.948 I/mono-stdout(30771): V7CryptomatorHelper
08-28 21:43:09.948 I/mono-stdout(30771): 
08-28 21:43:09.948 I/mono-stdout(30771): abPrimaryMasterKey: 7C-52-6E-4A-94-3C-C0-2A-80-5A-24-8B-B5-40-BC-D7-D8-5C-E4-A3-87-FF-35-97-E6-F3-52-88-64-9F-68-65-59-BD-D9-AD-E2-81-4B-E8
08-28 21:43:09.948 I/mono-stdout(30771): abHmacMasterKey: 65-6E-F9-0A-BA-62-DB-CE-44-8F-07-0A-1A-31-0E-3F-42-94-3A-56-E8-BE-AE-D0-8D-0F-47-FE-7F-F4-C7-7B-C7-8A-E7-13-3A-ED-27-05
08-28 21:43:09.948 I/mono-stdout(30771): abScryptSalt: EA-F0-56-84-3F-24-02-37
08-28 21:43:09.948 I/mono-stdout(30771): kek: D4-B3-67-E1-A6-87-54-92-E2-13-5D-A5-75-20-D8-16-7C-29-1A-8A-04-F6-5C-02-15-64-E2-2A-BA-AE-0D-CF
08-28 21:43:09.948 I/mono-stdout(30771): masterKey: 8A-72-B4-63-B6-31-69-FD-3C-31-DE-82-31-F8-69-36-41-CD-24-15-27-BD-F8-FC-8A-5E-EE-08-21-80-59-EB
08-28 21:43:09.948 I/mono-stdout(30771): macKey: EA-63-CA-B8-CF-61-8F-96-BE-EC-28-CC-EF-F1-9B-E1-0A-BB-41-5C-F2-B6-6E-9E-AD-D8-B5-A5-49-2E-CE-69
08-28 21:43:09.948 I/mono-stdout(30771): sivKey: EA-63-CA-B8-CF-61-8F-96-BE-EC-28-CC-EF-F1-9B-E1-0A-BB-41-5C-F2-B6-6E-9E-AD-D8-B5-A5-49-2E-CE-69-8A-72-B4-63-B6-31-69-FD-3C-31-DE-82-31-F8-69-36-41-CD-24-15-27-BD-F8-FC-8A-5E-EE-08-21-80-59-EB
08-28 21:43:09.948 I/mono-stdout(30771): new byte[0]: 
08-28 21:43:09.948 I/mono-stdout(30771): ciphertext: 43-D7-43-09-A1-75-09-DE-A4-39-4A-20-7C-96-D5-EB
08-28 21:43:09.948 I/mono-stdout(30771): hash: 43-D7-43-09-A1-75-09-DE-A4-39-4A-20-7C-96-D5-EB
08-28 21:43:09.948 I/mono-stdout(30771): fullDirName: D2AVRMFFXJTE7WMCHLJWODRTIG627UA4
08-28 21:43:09.948 I/mono-stdout(30771): physicalPathRoot: D2/AVRMFFXJTE7WMCHLJWODRTIG627UA4
```

**Comment by lellis1936** [comment]
Well it seems pretty clear to me that the bug lies in either the Miscreant library or the .Net hash implementations in the Android environment.   The good news is it is probably a simple fix but the trick is finding where the change needs to be made.  

One thing I'd suggest is to report this behavior as a  Miscreant issue.  It is _possible_ that the 4.6.2 bugfix might actually correct the error.  Note from the stackoverflow item you referenced that the fix has to be "activated" through a registry entry.  Not sure how that would work in Android.   On the other hand, if it were just a bug in 4.6.1 you'd expect _my_ build to be failing too.

You might have to be a simple sample app that demonstrates the Miscreant failure and showing the different results for Windows.

The Miscreant library is only being used in my demo for the single line of code:

            siv = Aead.CreateAesCmacSiv(sivKey);

Just as a test, you might next try hard-coding the correct hash value in the second line below:

           byte[] ciphertext = siv.Seal(new byte[0]);
           byte[] hash = sha1.ComputeHash(ciphertext);
  
Doing that would reveal whether the rest of the code is working without issue.   If it is a replacement Siv might be worth doing or finding.  A replacement Siv function would eliminate the need for Miscreant.  At the time I built the demo Miscreant was the only .Net library I could find.   

Keep me posted on your progress.

**Comment by cocoon** [comment]
Wow that was quick, thanks for your prompt reply!

Indeed it is working when hardcoding the value like this for Android:

```
string cipherstring = "96-67-5E-74-5E-F2-37-08-45-36-5B-07-47-09-AF-8B";
ciphertext = SoapHexBinary.Parse(cipherstring.Replace("-","")).Value; 

-->


08-29 09:40:54.354 I/mono-stdout(30970): ciphertext: 96-67-5E-74-5E-F2-37-08-45-36-5B-07-47-09-AF-8B
08-29 09:40:54.360 I/mono-stdout(30970): hash: 96-67-5E-74-5E-F2-37-08-45-36-5B-07-47-09-AF-8B
08-29 09:40:54.360 I/mono-stdout(30970): 
08-29 09:40:54.362 I/mono-stdout(30970): fullDirName: MV4GZEO6F54SH247AZHPEEGOCGZQVUJA
08-29 09:40:54.362 I/mono-stdout(30970): 
08-29 09:40:54.362 I/mono-stdout(30970): physicalPathRoot: MV/4GZEO6F54SH247AZHPEEGOCGZQVUJA
```


I just tried to create a Binding Library for Cryptomators "siv-mode":
https://github.com/cryptomator/siv-mode

And it works with v1.3.0:
https://mvnrepository.com/artifact/org.cryptomator/siv-mode/1.3.0
https://repo1.maven.org/maven2/org/cryptomator/siv-mode/1.3.0/siv-mode-1.3.0.jar

Here is the Binding Library for testing (Xamarin, MonoAndroid,Version=v9.0):
[siv-mode-binding-lib.zip](https://github.com/lellis1936/CryptomatorAccessDemo/files/5144909/siv-mode-binding-lib.zip)

Maybe this can replace Miscreant with siv-mode?

**Comment by cocoon** [comment]
Done, seems to work 🎉 


**CreateDirInfo**
```
        byte[] encryptedBytes = AES_SIV.Encrypt(masterKey, macKey, Encoding.UTF8.GetBytes(dirID));
        
        var dirIdHash =
            //Base32Encoding.ToString(sha1.ComputeHash(siv.Seal(Encoding.UTF8.GetBytes(dirID))));
            Base32Encoding.ToString(sha1.ComputeHash(encryptedBytes));
```


**DecryptFileName**
```
var ctrKey = masterKey;
        byte[] plaintextName = AES_SIV.Decrypt(ctrKey, macKey,encryptedName, Encoding.UTF8.GetBytes(parentDirId));
```

**Comment by lellis1936** [comment]
So the whole app is now working after replacing the Siv functions with your Java binding library?  

Ideally the app would be all c# or all Java, not a mix, yes?   Clearly there is something about the Miscreant library that causes it to fail in your environment.  You might consider letting the Miscreant people know your findings with an issue as they might be able to supply a simple fix.

**Comment by cocoon** [comment]
Report Done: https://github.com/miscreant/meta/issues/196

Yes the whole app is now working, I can list folders and files now.

Just some error catching in decoding, if for example wrong files are in the vault (in my case a desktop.ini found it's way into a folder somehow) and when these are to be decoded with base64 in ["DecryptFileName"](https://github.com/lellis1936/CryptomatorAccessDemo/blob/master/CryptomatorHelper/V7CryptomatorHelper.cs#L344)  it crashed, but that is not related to the crypto libs.
